### ISSUE TITLE
Is is possible to disable this package for specific modes?

### ISSUE THREAD

**Issue by alienbogart** [YourFin/evil-better-visual-line#5]

**Comment by YourFin** [comment]
It should be - if you look at how `evil-better-visual-line-on` is defined [here](https://github.com/YourFin/evil-better-visual-line/blob/4373f930ab1a8d3a2a90e68540967702313b2ce9/evil-better-visual-line.el#L61), you can replicate those bindings (or their inverse - i.e. keep the global binds, but rebind "j" and "k" to evil-next-line and evil-previous-line in those modes) on a mode-dependent basis with something like [general](https://github.com/noctuid/general.el). There are probably mechanisms within plain old emacs/evil to do this too, but I don't remember them off the top of my head.

The better way of doing this would be defining a minor mode for this package, bind the keys for the mode, and then that mode could be loaded with the normal hook mechanisms. 

I'm curious about your use case, but in general I'm not super interested in pulling that in to my own emacs config. However, something to the effect of:

    (define-minor-mode evil-better-visual-line-mode
      "Doc string here"
      :lighter "your short modeline name here"
      :keymap (make-sparse-keymap)
      :global nil)

    (evil-define-minor-mode-key 'visual 'evil-better-visual-line-mode "j" #'evil-better-visual-line-next-line)
    (evil-define-minor-mode-key 'visual 'evil-better-visual-line-mode "k" #'evil-better-visual-line-previous-line)

In your own config should cover that. I have not tested that code, but it should be a good starting point even if it doesn't work verbatim.

**Comment by YourFin** [comment]
I'm going to close this issue; feel free to ask for further clarification though.

**Comment by alienbogart** [comment]
This messes up with the Doom Dashboard.

**Comment by ErnestDong** [comment]
> This messes up with the Doom Dashboard.
```emacs-lisp
(define-key! +doom-dashboard-mode-map
  [remap evil-better-visual-line-next-line]     #'forward-button
  [remap evil-better-visual-line-previous-line] #'backward-button)
```
